# basic info
user_name: "zkz515"
repo_name: "cv-arxiv-daily"

show_badge: false
max_results: 50

publish_readme: true
publish_gitpage: true
publish_wechat: false

# file path 
json_readme_path: './docs/cv-arxiv-daily.json'
json_gitpage_path: './docs/cv-arxiv-daily-web.json'
json_wechat_path: './docs/cv-arxiv-daily-wechat.json'

md_readme_path: 'README.md'
md_gitpage_path: './docs/index.md'
md_wechat_path: './docs/wechat.md'

# keywords
keywords:
  "Robot & Agent":
    filters: ["Robot Learning", "Robot Policy", "Robot Policies", "Human-Robot", "Cross-Embodiment", "Robot Manipulation", "Robotic Manipulation"]
  "Vision Language Action Model":
    filters: ["Vision-Language-Action Model", "Vision Language Action Model", "VLA", "VLAs", "VLA Models"]
  "World Model & World Action":
    filters: ["World Model", "Video Model", "Video Action", "World Action", "VA", "WA", "WM"]
  "vlm":
    filters: ["Vision Language Model", "Spatial Reasoning", "Reward model"]
  "Robot": 
    filters: ["robot"]
#     filters: ["Prompt Tuning", "Prompt Learning", "Prompt", "Prompts"]
#   "Causal Learning":
#     filters: ["Causal Inference", "Causal Model", "Causal Discovery", "Causal Reasoning"]
